name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        cache: true

    - name: Build RPi
      run: go build -v -o relay-rpi ./...
      env:
        GOOS: linux
        GOARCH: arm
        GOARM: 5

    - name: Build OSX-amd64
      run: go build -v -o relay-osx ./...
      env:
        GOOS: darwin
        GOARCH: amd64
        
    - name: Build OSX-arm64
      run: go build -v -o relay-osx-arm ./...
      env:
        GOOS: darwin
        GOARCH: arm64
        
    - name: Build linux-mips-soft
      run: go build -v -o relay-linux-mips-soft -trimpath -ldflags="-s -w" ./...
      env:
        GOOS: linux
        GOARCH: mips
        GOMIPS: softfloat
    
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          relay-rpi
          relay-osx
          relay-osx-arm
          relay-linux-mips-soft

